### ISSUE TITLE
Can't install picamera module 

### ISSUE THREAD

**Issue by dennis08** [mayuanjason/mbot#2]
Dear Sir,

Another problem shows up. Can you install picamera on Jetson Nano?
$pipenv install picamera

Get failed 

jetbot@jetbot:~/mbot$ pipenv shell

(mbot) jetbot@jetbot:~/mbot$ pipenv install picamera

Installing picamera…
✔ Installation Succeeded 
Installing dependencies from Pipfile.lock (18aa4a)…
An error occurred while installing picamera==1.13 --hash=sha256:890815aa01e4d855a6a95dd3ad0953b872a6b954982106407df0c5a31a163e50! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/5 — 00:00:09
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/home/jetbot/.local/lib/python3.6/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting picamera==1.13 (from -r /tmp/pipenv-hq2oos8f-requirements/pipenv-fv861q_3-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/79/c4/80afe871d82ab1d5c9d8f0c0258228a8a0ed96db07a78ef17e7fba12fda8/picamera-1.13.tar.gz', 'Building wheels for collected packages: picamera', '  Building wheel for picamera (setup.py): started', "  Building wheel for picamera (setup.py): finished with status 'error'", '  Running setup.py clean for picamera', 'Failed to build picamera', 'Installing collected packages: picamera', '  Running setup.py install for picamera: started', "    Running setup.py install for picamera: finished with status 'error'"]
[pipenv.exceptions.InstallError]: ['ERROR: Complete output from command /home/jetbot/.local/share/virtualenvs/mbot-SgMflkEM/bin/python3.6m -u -c \'import setuptools, tokenize;__file__=\'"\'"\'/tmp/pip-install-dvnxlsxh/picamera/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d /tmp/pip-wheel-ufais3f8 --python-tag cp36:', '  ERROR: running bdist_wheel', '  running build', '  running build_py', '  creating build', '  creating build/lib', '  creating build/lib/picamera', '  copying picamera/streams.py -> build/lib/picamera', '  copying picamera/exc.py -> build/lib/picamera', '  copying picamera/frames.py -> build/lib/picamera', '  copying picamera/display.py -> build/lib/picamera', '  copying picamera/mmal.py -> build/lib/picamera', '  copying picamera/bcm_host.py -> build/lib/picamera', '  copying picamera/array.py -> build/lib/picamera', '  copying picamera/encoders.py -> build/lib/picamera', '  copying picamera/camera.py -> build/lib/picamera', '  copying picamera/__init__.py -> build/lib/picamera', '  copying picamera/mmalobj.py -> build/lib/picamera', '  copying picamera/color.py -> build/lib/picamera', '  copying picamera/renderers.py -> build/lib/picamera', '  running egg_info', '  writing picamera.egg-info/PKG-INFO', '  writing dependency_links to picamera.egg-info/dependency_links.txt', '  writing requirements to picamera.egg-info/requires.txt', '  writing top-level names to picamera.egg-info/top_level.txt', "  reading manifest file 'picamera.egg-info/SOURCES.txt'", "  reading manifest template 'MANIFEST.in'", "  no previously-included directories found matching 'debian'", "  no previously-included directories found matching 'docs'", "  writing manifest file 'picamera.egg-info/SOURCES.txt'", '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  installing to build/bdist.linux-aarch64/wheel', '  running install', '  Traceback (most recent call last):', '    File "<string>", line 1, in <module>', '    File "/tmp/pip-install-dvnxlsxh/picamera/setup.py", line 145, in <module>', '      main()', '    File "/tmp/pip-install-dvnxlsxh/picamera/setup.py", line 140, in main', "      cmdclass             = {'install': CustomInstallCommand},", '    File "/home/jetbot/.local/share/virtualenvs/mbot-SgMflkEM/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup', '      return distutils.core.setup(**attrs)', '    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup', '      dist.run_commands()', '    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands', '      self.run_command(cmd)', '    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command', '      cmd_obj.run()', '    File "/home/jetbot/.local/share/virtualenvs/mbot-SgMflkEM/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 228, in run', "      self.run_command('install')", '    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command', '      self.distribution.run_command(command)', '    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command', '      cmd_obj.run()', '    File "/tmp/pip-install-dvnxlsxh/picamera/setup.py", line 111, in run', "      raise ValueError('Unable to determine if this system is a Raspberry Pi')", '  ValueError: Unable to determine if this system is a Raspberry Pi', '  ----------------------------------------', '  ERROR: Failed building wheel for picamera', '    ERROR: Complete output from command /home/jetbot/.local/share/virtualenvs/mbot-SgMflkEM/bin/python3.6m -u -c \'import setuptools, tokenize;__file__=\'"\'"\'/tmp/pip-install-dvnxlsxh/picamera/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-e72o75ni/install-record.txt --single-version-externally-managed --compile --install-headers /home/jetbot/.local/share/virtualenvs/mbot-SgMflkEM/include/site/python3.6/picamera:', '    ERROR: running install', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/tmp/pip-install-dvnxlsxh/picamera/setup.py", line 145, in <module>', '        main()', '      File "/tmp/pip-install-dvnxlsxh/picamera/setup.py", line 140, in main', "        cmdclass             = {'install': CustomInstallCommand},", '      File "/home/jetbot/.local/share/virtualenvs/mbot-SgMflkEM/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup', '        return distutils.core.setup(**attrs)', '      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup', '        dist.run_commands()', '      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands', '        self.run_command(cmd)', '      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command', '        cmd_obj.run()', '      File "/tmp/pip-install-dvnxlsxh/picamera/setup.py", line 111, in run', "        raise ValueError('Unable to determine if this system is a Raspberry Pi')", '    ValueError: Unable to determine if this system is a Raspberry Pi', '    ----------------------------------------', 'ERROR: Command "/home/jetbot/.local/share/virtualenvs/mbot-SgMflkEM/bin/python3.6m -u -c \'import setuptools, tokenize;__file__=\'"\'"\'/tmp/pip-install-dvnxlsxh/picamera/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-e72o75ni/install-record.txt --single-version-externally-managed --compile --install-headers /home/jetbot/.local/share/virtualenvs/mbot-SgMflkEM/include/site/python3.6/picamera" failed with error code 1 in /tmp/pip-install-dvnxlsxh/picamera/']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:0

**Comment by dennis08** [comment]
I fixed it, install old version picamera module is fine.

**Comment by mayuanjason** [comment]
Hi dennis08,
I have refactoring the whole program and test it on my Jetbot, it can work now.
BTW, there is no need picamera any more, just check my latest Wiki for how to run the program.
Wiki: https://github.com/mayuanjason/mbot/wiki/Remote-Control
Hope you enjoy it.

**Comment by Tros-t** [comment]
what picamera version should I install 

I get error while installing this stuff for an error while making a .exe file using pyinstaller
